// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/client/agreement_products"
	"github.com/bjerkio/crayon-api-go/client/agreement_reports"
	"github.com/bjerkio/crayon-api-go/client/assets"
	"github.com/bjerkio/crayon-api-go/client/aws_accounts"
	"github.com/bjerkio/crayon-api-go/client/azure_plans"
	"github.com/bjerkio/crayon-api-go/client/billing_cycles"
	"github.com/bjerkio/crayon-api-go/client/billing_statements"
	"github.com/bjerkio/crayon-api-go/client/blog_items"
	"github.com/bjerkio/crayon-api-go/client/consumers"
	"github.com/bjerkio/crayon-api-go/client/crayon_accounts"
	"github.com/bjerkio/crayon-api-go/client/customer_tenant_agreements"
	"github.com/bjerkio/crayon-api-go/client/customer_tenants"
	"github.com/bjerkio/crayon-api-go/client/google_orders"
	"github.com/bjerkio/crayon-api-go/client/management_links"
	"github.com/bjerkio/crayon-api-go/client/organization_access"
	"github.com/bjerkio/crayon-api-go/client/organizations"
	"github.com/bjerkio/crayon-api-go/client/product_containers"
	"github.com/bjerkio/crayon-api-go/client/publishers"
	"github.com/bjerkio/crayon-api-go/client/regions"
	"github.com/bjerkio/crayon-api-go/client/reseller_sales_prices"
	"github.com/bjerkio/crayon-api-go/client/secrets"
	"github.com/bjerkio/crayon-api-go/client/subscriptions"
	"github.com/bjerkio/crayon-api-go/client/usage_cost"
	"github.com/bjerkio/crayon-api-go/client/users"
)

// Default crayon group customer API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "apiv1.crayon.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new crayon group customer API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *CrayonGroupCustomerAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new crayon group customer API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *CrayonGroupCustomerAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new crayon group customer API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *CrayonGroupCustomerAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(CrayonGroupCustomerAPI)
	cli.Transport = transport
	cli.AgreementProducts = agreement_products.New(transport, formats)
	cli.AgreementReports = agreement_reports.New(transport, formats)
	cli.Assets = assets.New(transport, formats)
	cli.AwsAccounts = aws_accounts.New(transport, formats)
	cli.AzurePlans = azure_plans.New(transport, formats)
	cli.BillingCycles = billing_cycles.New(transport, formats)
	cli.BillingStatements = billing_statements.New(transport, formats)
	cli.BlogItems = blog_items.New(transport, formats)
	cli.Consumers = consumers.New(transport, formats)
	cli.CrayonAccounts = crayon_accounts.New(transport, formats)
	cli.CustomerTenantAgreements = customer_tenant_agreements.New(transport, formats)
	cli.CustomerTenants = customer_tenants.New(transport, formats)
	cli.GoogleOrders = google_orders.New(transport, formats)
	cli.ManagementLinks = management_links.New(transport, formats)
	cli.OrganizationAccess = organization_access.New(transport, formats)
	cli.Organizations = organizations.New(transport, formats)
	cli.ProductContainers = product_containers.New(transport, formats)
	cli.Publishers = publishers.New(transport, formats)
	cli.Regions = regions.New(transport, formats)
	cli.ResellerSalesPrices = reseller_sales_prices.New(transport, formats)
	cli.Secrets = secrets.New(transport, formats)
	cli.Subscriptions = subscriptions.New(transport, formats)
	cli.UsageCost = usage_cost.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// CrayonGroupCustomerAPI is a client for crayon group customer API
type CrayonGroupCustomerAPI struct {
	AgreementProducts agreement_products.ClientService

	AgreementReports agreement_reports.ClientService

	Assets assets.ClientService

	AwsAccounts aws_accounts.ClientService

	AzurePlans azure_plans.ClientService

	BillingCycles billing_cycles.ClientService

	BillingStatements billing_statements.ClientService

	BlogItems blog_items.ClientService

	Consumers consumers.ClientService

	CrayonAccounts crayon_accounts.ClientService

	CustomerTenantAgreements customer_tenant_agreements.ClientService

	CustomerTenants customer_tenants.ClientService

	GoogleOrders google_orders.ClientService

	ManagementLinks management_links.ClientService

	OrganizationAccess organization_access.ClientService

	Organizations organizations.ClientService

	ProductContainers product_containers.ClientService

	Publishers publishers.ClientService

	Regions regions.ClientService

	ResellerSalesPrices reseller_sales_prices.ClientService

	Secrets secrets.ClientService

	Subscriptions subscriptions.ClientService

	UsageCost usage_cost.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *CrayonGroupCustomerAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.AgreementProducts.SetTransport(transport)
	c.AgreementReports.SetTransport(transport)
	c.Assets.SetTransport(transport)
	c.AwsAccounts.SetTransport(transport)
	c.AzurePlans.SetTransport(transport)
	c.BillingCycles.SetTransport(transport)
	c.BillingStatements.SetTransport(transport)
	c.BlogItems.SetTransport(transport)
	c.Consumers.SetTransport(transport)
	c.CrayonAccounts.SetTransport(transport)
	c.CustomerTenantAgreements.SetTransport(transport)
	c.CustomerTenants.SetTransport(transport)
	c.GoogleOrders.SetTransport(transport)
	c.ManagementLinks.SetTransport(transport)
	c.OrganizationAccess.SetTransport(transport)
	c.Organizations.SetTransport(transport)
	c.ProductContainers.SetTransport(transport)
	c.Publishers.SetTransport(transport)
	c.Regions.SetTransport(transport)
	c.ResellerSalesPrices.SetTransport(transport)
	c.Secrets.SetTransport(transport)
	c.Subscriptions.SetTransport(transport)
	c.UsageCost.SetTransport(transport)
	c.Users.SetTransport(transport)
}
