// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// PostSecretsReader is a Reader for the PostSecrets structure.
type PostSecretsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSecretsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSecretsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostSecretsOK creates a PostSecretsOK with default headers values
func NewPostSecretsOK() *PostSecretsOK {
	return &PostSecretsOK{}
}

/*PostSecretsOK handles this case with default header values.

Success
*/
type PostSecretsOK struct {
	Payload *models.Secret
}

func (o *PostSecretsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/Secrets][%d] postSecretsOK  %+v", 200, o.Payload)
}

func (o *PostSecretsOK) GetPayload() *models.Secret {
	return o.Payload
}

func (o *PostSecretsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Secret)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
