// Code generated by go-swagger; DO NOT EDIT.

package groupings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewCreateGroupingsParams creates a new CreateGroupingsParams object
// with the default values initialized.
func NewCreateGroupingsParams() *CreateGroupingsParams {
	var ()
	return &CreateGroupingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGroupingsParamsWithTimeout creates a new CreateGroupingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGroupingsParamsWithTimeout(timeout time.Duration) *CreateGroupingsParams {
	var ()
	return &CreateGroupingsParams{

		timeout: timeout,
	}
}

// NewCreateGroupingsParamsWithContext creates a new CreateGroupingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateGroupingsParamsWithContext(ctx context.Context) *CreateGroupingsParams {
	var ()
	return &CreateGroupingsParams{

		Context: ctx,
	}
}

// NewCreateGroupingsParamsWithHTTPClient creates a new CreateGroupingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateGroupingsParamsWithHTTPClient(client *http.Client) *CreateGroupingsParams {
	var ()
	return &CreateGroupingsParams{
		HTTPClient: client,
	}
}

/*CreateGroupingsParams contains all the parameters to send to the API endpoint
for the create groupings operation typically these are written to a http.Request
*/
type CreateGroupingsParams struct {

	/*Grouping*/
	Grouping *models.Grouping

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create groupings params
func (o *CreateGroupingsParams) WithTimeout(timeout time.Duration) *CreateGroupingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create groupings params
func (o *CreateGroupingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create groupings params
func (o *CreateGroupingsParams) WithContext(ctx context.Context) *CreateGroupingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create groupings params
func (o *CreateGroupingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create groupings params
func (o *CreateGroupingsParams) WithHTTPClient(client *http.Client) *CreateGroupingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create groupings params
func (o *CreateGroupingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGrouping adds the grouping to the create groupings params
func (o *CreateGroupingsParams) WithGrouping(grouping *models.Grouping) *CreateGroupingsParams {
	o.SetGrouping(grouping)
	return o
}

// SetGrouping adds the grouping to the create groupings params
func (o *CreateGroupingsParams) SetGrouping(grouping *models.Grouping) {
	o.Grouping = grouping
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGroupingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Grouping != nil {
		if err := r.SetBodyParam(o.Grouping); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
