// Code generated by go-swagger; DO NOT EDIT.

package invoice_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewCreateInvoiceProfilesParams creates a new CreateInvoiceProfilesParams object
// with the default values initialized.
func NewCreateInvoiceProfilesParams() *CreateInvoiceProfilesParams {
	var ()
	return &CreateInvoiceProfilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateInvoiceProfilesParamsWithTimeout creates a new CreateInvoiceProfilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateInvoiceProfilesParamsWithTimeout(timeout time.Duration) *CreateInvoiceProfilesParams {
	var ()
	return &CreateInvoiceProfilesParams{

		timeout: timeout,
	}
}

// NewCreateInvoiceProfilesParamsWithContext creates a new CreateInvoiceProfilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateInvoiceProfilesParamsWithContext(ctx context.Context) *CreateInvoiceProfilesParams {
	var ()
	return &CreateInvoiceProfilesParams{

		Context: ctx,
	}
}

// NewCreateInvoiceProfilesParamsWithHTTPClient creates a new CreateInvoiceProfilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateInvoiceProfilesParamsWithHTTPClient(client *http.Client) *CreateInvoiceProfilesParams {
	var ()
	return &CreateInvoiceProfilesParams{
		HTTPClient: client,
	}
}

/*CreateInvoiceProfilesParams contains all the parameters to send to the API endpoint
for the create invoice profiles operation typically these are written to a http.Request
*/
type CreateInvoiceProfilesParams struct {

	/*InvoiceProfile*/
	InvoiceProfile *models.InvoiceProfile

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) WithTimeout(timeout time.Duration) *CreateInvoiceProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) WithContext(ctx context.Context) *CreateInvoiceProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) WithHTTPClient(client *http.Client) *CreateInvoiceProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInvoiceProfile adds the invoiceProfile to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) WithInvoiceProfile(invoiceProfile *models.InvoiceProfile) *CreateInvoiceProfilesParams {
	o.SetInvoiceProfile(invoiceProfile)
	return o
}

// SetInvoiceProfile adds the invoiceProfile to the create invoice profiles params
func (o *CreateInvoiceProfilesParams) SetInvoiceProfile(invoiceProfile *models.InvoiceProfile) {
	o.InvoiceProfile = invoiceProfile
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInvoiceProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.InvoiceProfile != nil {
		if err := r.SetBodyParam(o.InvoiceProfile); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
