// Code generated by go-swagger; DO NOT EDIT.

package invoice_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewPutInvoiceProfilesParams creates a new PutInvoiceProfilesParams object
// with the default values initialized.
func NewPutInvoiceProfilesParams() *PutInvoiceProfilesParams {
	var ()
	return &PutInvoiceProfilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutInvoiceProfilesParamsWithTimeout creates a new PutInvoiceProfilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutInvoiceProfilesParamsWithTimeout(timeout time.Duration) *PutInvoiceProfilesParams {
	var ()
	return &PutInvoiceProfilesParams{

		timeout: timeout,
	}
}

// NewPutInvoiceProfilesParamsWithContext creates a new PutInvoiceProfilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutInvoiceProfilesParamsWithContext(ctx context.Context) *PutInvoiceProfilesParams {
	var ()
	return &PutInvoiceProfilesParams{

		Context: ctx,
	}
}

// NewPutInvoiceProfilesParamsWithHTTPClient creates a new PutInvoiceProfilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutInvoiceProfilesParamsWithHTTPClient(client *http.Client) *PutInvoiceProfilesParams {
	var ()
	return &PutInvoiceProfilesParams{
		HTTPClient: client,
	}
}

/*PutInvoiceProfilesParams contains all the parameters to send to the API endpoint
for the put invoice profiles operation typically these are written to a http.Request
*/
type PutInvoiceProfilesParams struct {

	/*ID*/
	ID int32
	/*InvoiceProfile*/
	InvoiceProfile *models.InvoiceProfile

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put invoice profiles params
func (o *PutInvoiceProfilesParams) WithTimeout(timeout time.Duration) *PutInvoiceProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put invoice profiles params
func (o *PutInvoiceProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put invoice profiles params
func (o *PutInvoiceProfilesParams) WithContext(ctx context.Context) *PutInvoiceProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put invoice profiles params
func (o *PutInvoiceProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put invoice profiles params
func (o *PutInvoiceProfilesParams) WithHTTPClient(client *http.Client) *PutInvoiceProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put invoice profiles params
func (o *PutInvoiceProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put invoice profiles params
func (o *PutInvoiceProfilesParams) WithID(id int32) *PutInvoiceProfilesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put invoice profiles params
func (o *PutInvoiceProfilesParams) SetID(id int32) {
	o.ID = id
}

// WithInvoiceProfile adds the invoiceProfile to the put invoice profiles params
func (o *PutInvoiceProfilesParams) WithInvoiceProfile(invoiceProfile *models.InvoiceProfile) *PutInvoiceProfilesParams {
	o.SetInvoiceProfile(invoiceProfile)
	return o
}

// SetInvoiceProfile adds the invoiceProfile to the put invoice profiles params
func (o *PutInvoiceProfilesParams) SetInvoiceProfile(invoiceProfile *models.InvoiceProfile) {
	o.InvoiceProfile = invoiceProfile
}

// WriteToRequest writes these params to a swagger request
func (o *PutInvoiceProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.InvoiceProfile != nil {
		if err := r.SetBodyParam(o.InvoiceProfile); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
