// Code generated by go-swagger; DO NOT EDIT.

package regions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// GetByRegionCodeReader is a Reader for the GetByRegionCode structure.
type GetByRegionCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetByRegionCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetByRegionCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetByRegionCodeOK creates a GetByRegionCodeOK with default headers values
func NewGetByRegionCodeOK() *GetByRegionCodeOK {
	return &GetByRegionCodeOK{}
}

/*GetByRegionCodeOK handles this case with default header values.

Success
*/
type GetByRegionCodeOK struct {
	Payload *models.Region
}

func (o *GetByRegionCodeOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/Regions/bycode][%d] getByRegionCodeOK  %+v", 200, o.Payload)
}

func (o *GetByRegionCodeOK) GetPayload() *models.Region {
	return o.Payload
}

func (o *GetByRegionCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Region)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
