// Code generated by go-swagger; DO NOT EDIT.

package organization_access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewUpdateOrganizationAccessParams creates a new UpdateOrganizationAccessParams object
// with the default values initialized.
func NewUpdateOrganizationAccessParams() *UpdateOrganizationAccessParams {
	var ()
	return &UpdateOrganizationAccessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOrganizationAccessParamsWithTimeout creates a new UpdateOrganizationAccessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateOrganizationAccessParamsWithTimeout(timeout time.Duration) *UpdateOrganizationAccessParams {
	var ()
	return &UpdateOrganizationAccessParams{

		timeout: timeout,
	}
}

// NewUpdateOrganizationAccessParamsWithContext creates a new UpdateOrganizationAccessParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateOrganizationAccessParamsWithContext(ctx context.Context) *UpdateOrganizationAccessParams {
	var ()
	return &UpdateOrganizationAccessParams{

		Context: ctx,
	}
}

// NewUpdateOrganizationAccessParamsWithHTTPClient creates a new UpdateOrganizationAccessParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateOrganizationAccessParamsWithHTTPClient(client *http.Client) *UpdateOrganizationAccessParams {
	var ()
	return &UpdateOrganizationAccessParams{
		HTTPClient: client,
	}
}

/*UpdateOrganizationAccessParams contains all the parameters to send to the API endpoint
for the update organization access operation typically these are written to a http.Request
*/
type UpdateOrganizationAccessParams struct {

	/*List*/
	List []*models.OrganizationAccess

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update organization access params
func (o *UpdateOrganizationAccessParams) WithTimeout(timeout time.Duration) *UpdateOrganizationAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update organization access params
func (o *UpdateOrganizationAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update organization access params
func (o *UpdateOrganizationAccessParams) WithContext(ctx context.Context) *UpdateOrganizationAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update organization access params
func (o *UpdateOrganizationAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update organization access params
func (o *UpdateOrganizationAccessParams) WithHTTPClient(client *http.Client) *UpdateOrganizationAccessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update organization access params
func (o *UpdateOrganizationAccessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithList adds the list to the update organization access params
func (o *UpdateOrganizationAccessParams) WithList(list []*models.OrganizationAccess) *UpdateOrganizationAccessParams {
	o.SetList(list)
	return o
}

// SetList adds the list to the update organization access params
func (o *UpdateOrganizationAccessParams) SetList(list []*models.OrganizationAccess) {
	o.List = list
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOrganizationAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.List != nil {
		if err := r.SetBodyParam(o.List); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
