// Code generated by go-swagger; DO NOT EDIT.

package aws_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAwsAccountByIDParams creates a new GetAwsAccountByIDParams object
// with the default values initialized.
func NewGetAwsAccountByIDParams() *GetAwsAccountByIDParams {
	var ()
	return &GetAwsAccountByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAwsAccountByIDParamsWithTimeout creates a new GetAwsAccountByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAwsAccountByIDParamsWithTimeout(timeout time.Duration) *GetAwsAccountByIDParams {
	var ()
	return &GetAwsAccountByIDParams{

		timeout: timeout,
	}
}

// NewGetAwsAccountByIDParamsWithContext creates a new GetAwsAccountByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAwsAccountByIDParamsWithContext(ctx context.Context) *GetAwsAccountByIDParams {
	var ()
	return &GetAwsAccountByIDParams{

		Context: ctx,
	}
}

// NewGetAwsAccountByIDParamsWithHTTPClient creates a new GetAwsAccountByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAwsAccountByIDParamsWithHTTPClient(client *http.Client) *GetAwsAccountByIDParams {
	var ()
	return &GetAwsAccountByIDParams{
		HTTPClient: client,
	}
}

/*GetAwsAccountByIDParams contains all the parameters to send to the API endpoint
for the get aws account by Id operation typically these are written to a http.Request
*/
type GetAwsAccountByIDParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get aws account by Id params
func (o *GetAwsAccountByIDParams) WithTimeout(timeout time.Duration) *GetAwsAccountByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get aws account by Id params
func (o *GetAwsAccountByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get aws account by Id params
func (o *GetAwsAccountByIDParams) WithContext(ctx context.Context) *GetAwsAccountByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get aws account by Id params
func (o *GetAwsAccountByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get aws account by Id params
func (o *GetAwsAccountByIDParams) WithHTTPClient(client *http.Client) *GetAwsAccountByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get aws account by Id params
func (o *GetAwsAccountByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get aws account by Id params
func (o *GetAwsAccountByIDParams) WithID(id int32) *GetAwsAccountByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get aws account by Id params
func (o *GetAwsAccountByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAwsAccountByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
