// Code generated by go-swagger; DO NOT EDIT.

package aws_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// PutAwsAccountsReader is a Reader for the PutAwsAccounts structure.
type PutAwsAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAwsAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAwsAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAwsAccountsOK creates a PutAwsAccountsOK with default headers values
func NewPutAwsAccountsOK() *PutAwsAccountsOK {
	return &PutAwsAccountsOK{}
}

/*PutAwsAccountsOK handles this case with default header values.

Success
*/
type PutAwsAccountsOK struct {
	Payload *models.AwsAccount
}

func (o *PutAwsAccountsOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/AwsAccounts/{id}][%d] putAwsAccountsOK  %+v", 200, o.Payload)
}

func (o *PutAwsAccountsOK) GetPayload() *models.AwsAccount {
	return o.Payload
}

func (o *PutAwsAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AwsAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
