// Code generated by go-swagger; DO NOT EDIT.

package aws_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// UpdateAwsAccountsReader is a Reader for the UpdateAwsAccounts structure.
type UpdateAwsAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAwsAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAwsAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateAwsAccountsOK creates a UpdateAwsAccountsOK with default headers values
func NewUpdateAwsAccountsOK() *UpdateAwsAccountsOK {
	return &UpdateAwsAccountsOK{}
}

/*UpdateAwsAccountsOK handles this case with default header values.

Success
*/
type UpdateAwsAccountsOK struct {
	Payload *models.AwsAccount
}

func (o *UpdateAwsAccountsOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/AwsAccounts/{id}][%d] updateAwsAccountsOK  %+v", 200, o.Payload)
}

func (o *UpdateAwsAccountsOK) GetPayload() *models.AwsAccount {
	return o.Payload
}

func (o *UpdateAwsAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AwsAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
