// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteSubscriptionTagsParams creates a new DeleteSubscriptionTagsParams object
// with the default values initialized.
func NewDeleteSubscriptionTagsParams() *DeleteSubscriptionTagsParams {
	var ()
	return &DeleteSubscriptionTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSubscriptionTagsParamsWithTimeout creates a new DeleteSubscriptionTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSubscriptionTagsParamsWithTimeout(timeout time.Duration) *DeleteSubscriptionTagsParams {
	var ()
	return &DeleteSubscriptionTagsParams{

		timeout: timeout,
	}
}

// NewDeleteSubscriptionTagsParamsWithContext creates a new DeleteSubscriptionTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSubscriptionTagsParamsWithContext(ctx context.Context) *DeleteSubscriptionTagsParams {
	var ()
	return &DeleteSubscriptionTagsParams{

		Context: ctx,
	}
}

// NewDeleteSubscriptionTagsParamsWithHTTPClient creates a new DeleteSubscriptionTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSubscriptionTagsParamsWithHTTPClient(client *http.Client) *DeleteSubscriptionTagsParams {
	var ()
	return &DeleteSubscriptionTagsParams{
		HTTPClient: client,
	}
}

/*DeleteSubscriptionTagsParams contains all the parameters to send to the API endpoint
for the delete subscription tags operation typically these are written to a http.Request
*/
type DeleteSubscriptionTagsParams struct {

	/*SubscriptionID*/
	SubscriptionID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) WithTimeout(timeout time.Duration) *DeleteSubscriptionTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) WithContext(ctx context.Context) *DeleteSubscriptionTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) WithHTTPClient(client *http.Client) *DeleteSubscriptionTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriptionID adds the subscriptionID to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) WithSubscriptionID(subscriptionID int32) *DeleteSubscriptionTagsParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the delete subscription tags params
func (o *DeleteSubscriptionTagsParams) SetSubscriptionID(subscriptionID int32) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSubscriptionTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", swag.FormatInt32(o.SubscriptionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
