// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetActivationLinkAsyncParams creates a new GetActivationLinkAsyncParams object
// with the default values initialized.
func NewGetActivationLinkAsyncParams() *GetActivationLinkAsyncParams {
	var ()
	return &GetActivationLinkAsyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActivationLinkAsyncParamsWithTimeout creates a new GetActivationLinkAsyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActivationLinkAsyncParamsWithTimeout(timeout time.Duration) *GetActivationLinkAsyncParams {
	var ()
	return &GetActivationLinkAsyncParams{

		timeout: timeout,
	}
}

// NewGetActivationLinkAsyncParamsWithContext creates a new GetActivationLinkAsyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActivationLinkAsyncParamsWithContext(ctx context.Context) *GetActivationLinkAsyncParams {
	var ()
	return &GetActivationLinkAsyncParams{

		Context: ctx,
	}
}

// NewGetActivationLinkAsyncParamsWithHTTPClient creates a new GetActivationLinkAsyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActivationLinkAsyncParamsWithHTTPClient(client *http.Client) *GetActivationLinkAsyncParams {
	var ()
	return &GetActivationLinkAsyncParams{
		HTTPClient: client,
	}
}

/*GetActivationLinkAsyncParams contains all the parameters to send to the API endpoint
for the get activation link async operation typically these are written to a http.Request
*/
type GetActivationLinkAsyncParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get activation link async params
func (o *GetActivationLinkAsyncParams) WithTimeout(timeout time.Duration) *GetActivationLinkAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get activation link async params
func (o *GetActivationLinkAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get activation link async params
func (o *GetActivationLinkAsyncParams) WithContext(ctx context.Context) *GetActivationLinkAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get activation link async params
func (o *GetActivationLinkAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get activation link async params
func (o *GetActivationLinkAsyncParams) WithHTTPClient(client *http.Client) *GetActivationLinkAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get activation link async params
func (o *GetActivationLinkAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get activation link async params
func (o *GetActivationLinkAsyncParams) WithID(id int32) *GetActivationLinkAsyncParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get activation link async params
func (o *GetActivationLinkAsyncParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetActivationLinkAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
