// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSubscriptionAddonsParams creates a new GetSubscriptionAddonsParams object
// with the default values initialized.
func NewGetSubscriptionAddonsParams() *GetSubscriptionAddonsParams {
	var ()
	return &GetSubscriptionAddonsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubscriptionAddonsParamsWithTimeout creates a new GetSubscriptionAddonsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubscriptionAddonsParamsWithTimeout(timeout time.Duration) *GetSubscriptionAddonsParams {
	var ()
	return &GetSubscriptionAddonsParams{

		timeout: timeout,
	}
}

// NewGetSubscriptionAddonsParamsWithContext creates a new GetSubscriptionAddonsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubscriptionAddonsParamsWithContext(ctx context.Context) *GetSubscriptionAddonsParams {
	var ()
	return &GetSubscriptionAddonsParams{

		Context: ctx,
	}
}

// NewGetSubscriptionAddonsParamsWithHTTPClient creates a new GetSubscriptionAddonsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubscriptionAddonsParamsWithHTTPClient(client *http.Client) *GetSubscriptionAddonsParams {
	var ()
	return &GetSubscriptionAddonsParams{
		HTTPClient: client,
	}
}

/*GetSubscriptionAddonsParams contains all the parameters to send to the API endpoint
for the get subscription addons operation typically these are written to a http.Request
*/
type GetSubscriptionAddonsParams struct {

	/*SubscriptionID*/
	SubscriptionID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get subscription addons params
func (o *GetSubscriptionAddonsParams) WithTimeout(timeout time.Duration) *GetSubscriptionAddonsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subscription addons params
func (o *GetSubscriptionAddonsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subscription addons params
func (o *GetSubscriptionAddonsParams) WithContext(ctx context.Context) *GetSubscriptionAddonsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subscription addons params
func (o *GetSubscriptionAddonsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subscription addons params
func (o *GetSubscriptionAddonsParams) WithHTTPClient(client *http.Client) *GetSubscriptionAddonsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subscription addons params
func (o *GetSubscriptionAddonsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriptionID adds the subscriptionID to the get subscription addons params
func (o *GetSubscriptionAddonsParams) WithSubscriptionID(subscriptionID int32) *GetSubscriptionAddonsParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the get subscription addons params
func (o *GetSubscriptionAddonsParams) SetSubscriptionID(subscriptionID int32) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubscriptionAddonsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", swag.FormatInt32(o.SubscriptionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
