// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// PostSubscriptionConversionReader is a Reader for the PostSubscriptionConversion structure.
type PostSubscriptionConversionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSubscriptionConversionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSubscriptionConversionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostSubscriptionConversionOK creates a PostSubscriptionConversionOK with default headers values
func NewPostSubscriptionConversionOK() *PostSubscriptionConversionOK {
	return &PostSubscriptionConversionOK{}
}

/*PostSubscriptionConversionOK handles this case with default header values.

Success
*/
type PostSubscriptionConversionOK struct {
	Payload *models.SubscriptionDetailed
}

func (o *PostSubscriptionConversionOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/Subscriptions/{subscriptionId}/conversions][%d] postSubscriptionConversionOK  %+v", 200, o.Payload)
}

func (o *PostSubscriptionConversionOK) GetPayload() *models.SubscriptionDetailed {
	return o.Payload
}

func (o *PostSubscriptionConversionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubscriptionDetailed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
