// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationSalesContactParams creates a new GetOrganizationSalesContactParams object
// with the default values initialized.
func NewGetOrganizationSalesContactParams() *GetOrganizationSalesContactParams {
	var ()
	return &GetOrganizationSalesContactParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationSalesContactParamsWithTimeout creates a new GetOrganizationSalesContactParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationSalesContactParamsWithTimeout(timeout time.Duration) *GetOrganizationSalesContactParams {
	var ()
	return &GetOrganizationSalesContactParams{

		timeout: timeout,
	}
}

// NewGetOrganizationSalesContactParamsWithContext creates a new GetOrganizationSalesContactParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationSalesContactParamsWithContext(ctx context.Context) *GetOrganizationSalesContactParams {
	var ()
	return &GetOrganizationSalesContactParams{

		Context: ctx,
	}
}

// NewGetOrganizationSalesContactParamsWithHTTPClient creates a new GetOrganizationSalesContactParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationSalesContactParamsWithHTTPClient(client *http.Client) *GetOrganizationSalesContactParams {
	var ()
	return &GetOrganizationSalesContactParams{
		HTTPClient: client,
	}
}

/*GetOrganizationSalesContactParams contains all the parameters to send to the API endpoint
for the get organization sales contact operation typically these are written to a http.Request
*/
type GetOrganizationSalesContactParams struct {

	/*OrganizationID*/
	OrganizationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) WithTimeout(timeout time.Duration) *GetOrganizationSalesContactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) WithContext(ctx context.Context) *GetOrganizationSalesContactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) WithHTTPClient(client *http.Client) *GetOrganizationSalesContactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) WithOrganizationID(organizationID int32) *GetOrganizationSalesContactParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization sales contact params
func (o *GetOrganizationSalesContactParams) SetOrganizationID(organizationID int32) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationSalesContactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", swag.FormatInt32(o.OrganizationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
