// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHasAccessAsyncParams creates a new HasAccessAsyncParams object
// with the default values initialized.
func NewHasAccessAsyncParams() *HasAccessAsyncParams {
	var ()
	return &HasAccessAsyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHasAccessAsyncParamsWithTimeout creates a new HasAccessAsyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHasAccessAsyncParamsWithTimeout(timeout time.Duration) *HasAccessAsyncParams {
	var ()
	return &HasAccessAsyncParams{

		timeout: timeout,
	}
}

// NewHasAccessAsyncParamsWithContext creates a new HasAccessAsyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewHasAccessAsyncParamsWithContext(ctx context.Context) *HasAccessAsyncParams {
	var ()
	return &HasAccessAsyncParams{

		Context: ctx,
	}
}

// NewHasAccessAsyncParamsWithHTTPClient creates a new HasAccessAsyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHasAccessAsyncParamsWithHTTPClient(client *http.Client) *HasAccessAsyncParams {
	var ()
	return &HasAccessAsyncParams{
		HTTPClient: client,
	}
}

/*HasAccessAsyncParams contains all the parameters to send to the API endpoint
for the has access async operation typically these are written to a http.Request
*/
type HasAccessAsyncParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the has access async params
func (o *HasAccessAsyncParams) WithTimeout(timeout time.Duration) *HasAccessAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the has access async params
func (o *HasAccessAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the has access async params
func (o *HasAccessAsyncParams) WithContext(ctx context.Context) *HasAccessAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the has access async params
func (o *HasAccessAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the has access async params
func (o *HasAccessAsyncParams) WithHTTPClient(client *http.Client) *HasAccessAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the has access async params
func (o *HasAccessAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the has access async params
func (o *HasAccessAsyncParams) WithID(id int32) *HasAccessAsyncParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the has access async params
func (o *HasAccessAsyncParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *HasAccessAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
