// Code generated by go-swagger; DO NOT EDIT.

package management_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// GetGroupedReader is a Reader for the GetGrouped structure.
type GetGroupedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGroupedOK creates a GetGroupedOK with default headers values
func NewGetGroupedOK() *GetGroupedOK {
	return &GetGroupedOK{}
}

/*GetGroupedOK handles this case with default header values.

Success
*/
type GetGroupedOK struct {
	Payload *models.APICollectionOfManagementLinkGrouped
}

func (o *GetGroupedOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/ManagementLinks/grouped][%d] getGroupedOK  %+v", 200, o.Payload)
}

func (o *GetGroupedOK) GetPayload() *models.APICollectionOfManagementLinkGrouped {
	return o.Payload
}

func (o *GetGroupedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICollectionOfManagementLinkGrouped)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
