// Code generated by go-swagger; DO NOT EDIT.

package usage_cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetForOrganizationParams creates a new GetForOrganizationParams object
// with the default values initialized.
func NewGetForOrganizationParams() *GetForOrganizationParams {
	var ()
	return &GetForOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetForOrganizationParamsWithTimeout creates a new GetForOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetForOrganizationParamsWithTimeout(timeout time.Duration) *GetForOrganizationParams {
	var ()
	return &GetForOrganizationParams{

		timeout: timeout,
	}
}

// NewGetForOrganizationParamsWithContext creates a new GetForOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetForOrganizationParamsWithContext(ctx context.Context) *GetForOrganizationParams {
	var ()
	return &GetForOrganizationParams{

		Context: ctx,
	}
}

// NewGetForOrganizationParamsWithHTTPClient creates a new GetForOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetForOrganizationParamsWithHTTPClient(client *http.Client) *GetForOrganizationParams {
	var ()
	return &GetForOrganizationParams{
		HTTPClient: client,
	}
}

/*GetForOrganizationParams contains all the parameters to send to the API endpoint
for the get for organization operation typically these are written to a http.Request
*/
type GetForOrganizationParams struct {

	/*From*/
	From *strfmt.DateTime
	/*OrganizationID*/
	OrganizationID int32
	/*To*/
	To *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get for organization params
func (o *GetForOrganizationParams) WithTimeout(timeout time.Duration) *GetForOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get for organization params
func (o *GetForOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get for organization params
func (o *GetForOrganizationParams) WithContext(ctx context.Context) *GetForOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get for organization params
func (o *GetForOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get for organization params
func (o *GetForOrganizationParams) WithHTTPClient(client *http.Client) *GetForOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get for organization params
func (o *GetForOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the get for organization params
func (o *GetForOrganizationParams) WithFrom(from *strfmt.DateTime) *GetForOrganizationParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get for organization params
func (o *GetForOrganizationParams) SetFrom(from *strfmt.DateTime) {
	o.From = from
}

// WithOrganizationID adds the organizationID to the get for organization params
func (o *GetForOrganizationParams) WithOrganizationID(organizationID int32) *GetForOrganizationParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get for organization params
func (o *GetForOrganizationParams) SetOrganizationID(organizationID int32) {
	o.OrganizationID = organizationID
}

// WithTo adds the to to the get for organization params
func (o *GetForOrganizationParams) WithTo(to *strfmt.DateTime) *GetForOrganizationParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get for organization params
func (o *GetForOrganizationParams) SetTo(to *strfmt.DateTime) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *GetForOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom strfmt.DateTime
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom.String()
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", swag.FormatInt32(o.OrganizationID)); err != nil {
		return err
	}

	if o.To != nil {

		// query param to
		var qrTo strfmt.DateTime
		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo.String()
		if qTo != "" {
			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
