// Code generated by go-swagger; DO NOT EDIT.

package usage_cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewPostAPIV1UsageCostGetForCategoryParams creates a new PostAPIV1UsageCostGetForCategoryParams object
// with the default values initialized.
func NewPostAPIV1UsageCostGetForCategoryParams() *PostAPIV1UsageCostGetForCategoryParams {
	var ()
	return &PostAPIV1UsageCostGetForCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1UsageCostGetForCategoryParamsWithTimeout creates a new PostAPIV1UsageCostGetForCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV1UsageCostGetForCategoryParamsWithTimeout(timeout time.Duration) *PostAPIV1UsageCostGetForCategoryParams {
	var ()
	return &PostAPIV1UsageCostGetForCategoryParams{

		timeout: timeout,
	}
}

// NewPostAPIV1UsageCostGetForCategoryParamsWithContext creates a new PostAPIV1UsageCostGetForCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV1UsageCostGetForCategoryParamsWithContext(ctx context.Context) *PostAPIV1UsageCostGetForCategoryParams {
	var ()
	return &PostAPIV1UsageCostGetForCategoryParams{

		Context: ctx,
	}
}

// NewPostAPIV1UsageCostGetForCategoryParamsWithHTTPClient creates a new PostAPIV1UsageCostGetForCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV1UsageCostGetForCategoryParamsWithHTTPClient(client *http.Client) *PostAPIV1UsageCostGetForCategoryParams {
	var ()
	return &PostAPIV1UsageCostGetForCategoryParams{
		HTTPClient: client,
	}
}

/*PostAPIV1UsageCostGetForCategoryParams contains all the parameters to send to the API endpoint
for the post API v1 usage cost get for category operation typically these are written to a http.Request
*/
type PostAPIV1UsageCostGetForCategoryParams struct {

	/*Model*/
	Model *models.CategoryUsageCostRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) WithTimeout(timeout time.Duration) *PostAPIV1UsageCostGetForCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) WithContext(ctx context.Context) *PostAPIV1UsageCostGetForCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) WithHTTPClient(client *http.Client) *PostAPIV1UsageCostGetForCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModel adds the model to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) WithModel(model *models.CategoryUsageCostRequest) *PostAPIV1UsageCostGetForCategoryParams {
	o.SetModel(model)
	return o
}

// SetModel adds the model to the post API v1 usage cost get for category params
func (o *PostAPIV1UsageCostGetForCategoryParams) SetModel(model *models.CategoryUsageCostRequest) {
	o.Model = model
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1UsageCostGetForCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Model != nil {
		if err := r.SetBodyParam(o.Model); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
