// Code generated by go-swagger; DO NOT EDIT.

package usage_cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// PostAPIV1UsageCostGetForSubscriptionResourceGroupsReader is a Reader for the PostAPIV1UsageCostGetForSubscriptionResourceGroups structure.
type PostAPIV1UsageCostGetForSubscriptionResourceGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1UsageCostGetForSubscriptionResourceGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1UsageCostGetForSubscriptionResourceGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV1UsageCostGetForSubscriptionResourceGroupsOK creates a PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK with default headers values
func NewPostAPIV1UsageCostGetForSubscriptionResourceGroupsOK() *PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK {
	return &PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK{}
}

/*PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK handles this case with default header values.

Success
*/
type PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK struct {
	Payload *models.APICollectionOfSubscriptionResourceGroupUsageCost
}

func (o *PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/UsageCost/getForSubscription/resourceGroups][%d] postApiV1UsageCostGetForSubscriptionResourceGroupsOK  %+v", 200, o.Payload)
}

func (o *PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK) GetPayload() *models.APICollectionOfSubscriptionResourceGroupUsageCost {
	return o.Payload
}

func (o *PostAPIV1UsageCostGetForSubscriptionResourceGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICollectionOfSubscriptionResourceGroupUsageCost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
