// Code generated by go-swagger; DO NOT EDIT.

package usage_cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// PostAPIV1UsageCostGetForResourceGroupReader is a Reader for the PostAPIV1UsageCostGetForResourceGroup structure.
type PostAPIV1UsageCostGetForResourceGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1UsageCostGetForResourceGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1UsageCostGetForResourceGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIV1UsageCostGetForResourceGroupOK creates a PostAPIV1UsageCostGetForResourceGroupOK with default headers values
func NewPostAPIV1UsageCostGetForResourceGroupOK() *PostAPIV1UsageCostGetForResourceGroupOK {
	return &PostAPIV1UsageCostGetForResourceGroupOK{}
}

/*PostAPIV1UsageCostGetForResourceGroupOK handles this case with default header values.

Success
*/
type PostAPIV1UsageCostGetForResourceGroupOK struct {
	Payload *models.APICollectionOfResourceGroupUsageCost
}

func (o *PostAPIV1UsageCostGetForResourceGroupOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/UsageCost/getForResourceGroup][%d] postApiV1UsageCostGetForResourceGroupOK  %+v", 200, o.Payload)
}

func (o *PostAPIV1UsageCostGetForResourceGroupOK) GetPayload() *models.APICollectionOfResourceGroupUsageCost {
	return o.Payload
}

func (o *PostAPIV1UsageCostGetForResourceGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICollectionOfResourceGroupUsageCost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
