// Code generated by go-swagger; DO NOT EDIT.

package usage_cost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewPostAPIV1UsageCostGetForSubscriptionParams creates a new PostAPIV1UsageCostGetForSubscriptionParams object
// with the default values initialized.
func NewPostAPIV1UsageCostGetForSubscriptionParams() *PostAPIV1UsageCostGetForSubscriptionParams {
	var ()
	return &PostAPIV1UsageCostGetForSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1UsageCostGetForSubscriptionParamsWithTimeout creates a new PostAPIV1UsageCostGetForSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV1UsageCostGetForSubscriptionParamsWithTimeout(timeout time.Duration) *PostAPIV1UsageCostGetForSubscriptionParams {
	var ()
	return &PostAPIV1UsageCostGetForSubscriptionParams{

		timeout: timeout,
	}
}

// NewPostAPIV1UsageCostGetForSubscriptionParamsWithContext creates a new PostAPIV1UsageCostGetForSubscriptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV1UsageCostGetForSubscriptionParamsWithContext(ctx context.Context) *PostAPIV1UsageCostGetForSubscriptionParams {
	var ()
	return &PostAPIV1UsageCostGetForSubscriptionParams{

		Context: ctx,
	}
}

// NewPostAPIV1UsageCostGetForSubscriptionParamsWithHTTPClient creates a new PostAPIV1UsageCostGetForSubscriptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV1UsageCostGetForSubscriptionParamsWithHTTPClient(client *http.Client) *PostAPIV1UsageCostGetForSubscriptionParams {
	var ()
	return &PostAPIV1UsageCostGetForSubscriptionParams{
		HTTPClient: client,
	}
}

/*PostAPIV1UsageCostGetForSubscriptionParams contains all the parameters to send to the API endpoint
for the post API v1 usage cost get for subscription operation typically these are written to a http.Request
*/
type PostAPIV1UsageCostGetForSubscriptionParams struct {

	/*Model*/
	Model *models.SubscriptionUsageCostRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) WithTimeout(timeout time.Duration) *PostAPIV1UsageCostGetForSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) WithContext(ctx context.Context) *PostAPIV1UsageCostGetForSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) WithHTTPClient(client *http.Client) *PostAPIV1UsageCostGetForSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModel adds the model to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) WithModel(model *models.SubscriptionUsageCostRequest) *PostAPIV1UsageCostGetForSubscriptionParams {
	o.SetModel(model)
	return o
}

// SetModel adds the model to the post API v1 usage cost get for subscription params
func (o *PostAPIV1UsageCostGetForSubscriptionParams) SetModel(model *models.SubscriptionUsageCostRequest) {
	o.Model = model
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1UsageCostGetForSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Model != nil {
		if err := r.SetBodyParam(o.Model); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
