// Code generated by go-swagger; DO NOT EDIT.

package agreement_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSupportedBillingCyclesParams creates a new GetSupportedBillingCyclesParams object
// with the default values initialized.
func NewGetSupportedBillingCyclesParams() *GetSupportedBillingCyclesParams {
	var ()
	return &GetSupportedBillingCyclesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSupportedBillingCyclesParamsWithTimeout creates a new GetSupportedBillingCyclesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSupportedBillingCyclesParamsWithTimeout(timeout time.Duration) *GetSupportedBillingCyclesParams {
	var ()
	return &GetSupportedBillingCyclesParams{

		timeout: timeout,
	}
}

// NewGetSupportedBillingCyclesParamsWithContext creates a new GetSupportedBillingCyclesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSupportedBillingCyclesParamsWithContext(ctx context.Context) *GetSupportedBillingCyclesParams {
	var ()
	return &GetSupportedBillingCyclesParams{

		Context: ctx,
	}
}

// NewGetSupportedBillingCyclesParamsWithHTTPClient creates a new GetSupportedBillingCyclesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSupportedBillingCyclesParamsWithHTTPClient(client *http.Client) *GetSupportedBillingCyclesParams {
	var ()
	return &GetSupportedBillingCyclesParams{
		HTTPClient: client,
	}
}

/*GetSupportedBillingCyclesParams contains all the parameters to send to the API endpoint
for the get supported billing cycles operation typically these are written to a http.Request
*/
type GetSupportedBillingCyclesParams struct {

	/*PartNumber*/
	PartNumber string
	/*ResellerCustomerID*/
	ResellerCustomerID *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) WithTimeout(timeout time.Duration) *GetSupportedBillingCyclesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) WithContext(ctx context.Context) *GetSupportedBillingCyclesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) WithHTTPClient(client *http.Client) *GetSupportedBillingCyclesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPartNumber adds the partNumber to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) WithPartNumber(partNumber string) *GetSupportedBillingCyclesParams {
	o.SetPartNumber(partNumber)
	return o
}

// SetPartNumber adds the partNumber to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) SetPartNumber(partNumber string) {
	o.PartNumber = partNumber
}

// WithResellerCustomerID adds the resellerCustomerID to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) WithResellerCustomerID(resellerCustomerID *int32) *GetSupportedBillingCyclesParams {
	o.SetResellerCustomerID(resellerCustomerID)
	return o
}

// SetResellerCustomerID adds the resellerCustomerId to the get supported billing cycles params
func (o *GetSupportedBillingCyclesParams) SetResellerCustomerID(resellerCustomerID *int32) {
	o.ResellerCustomerID = resellerCustomerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSupportedBillingCyclesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param partNumber
	if err := r.SetPathParam("partNumber", o.PartNumber); err != nil {
		return err
	}

	if o.ResellerCustomerID != nil {

		// query param resellerCustomerId
		var qrResellerCustomerID int32
		if o.ResellerCustomerID != nil {
			qrResellerCustomerID = *o.ResellerCustomerID
		}
		qResellerCustomerID := swag.FormatInt32(qrResellerCustomerID)
		if qResellerCustomerID != "" {
			if err := r.SetQueryParam("resellerCustomerId", qResellerCustomerID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
