// Code generated by go-swagger; DO NOT EDIT.

package billing_statements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReconciliationFileParams creates a new GetReconciliationFileParams object
// with the default values initialized.
func NewGetReconciliationFileParams() *GetReconciliationFileParams {
	var ()
	return &GetReconciliationFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReconciliationFileParamsWithTimeout creates a new GetReconciliationFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReconciliationFileParamsWithTimeout(timeout time.Duration) *GetReconciliationFileParams {
	var ()
	return &GetReconciliationFileParams{

		timeout: timeout,
	}
}

// NewGetReconciliationFileParamsWithContext creates a new GetReconciliationFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReconciliationFileParamsWithContext(ctx context.Context) *GetReconciliationFileParams {
	var ()
	return &GetReconciliationFileParams{

		Context: ctx,
	}
}

// NewGetReconciliationFileParamsWithHTTPClient creates a new GetReconciliationFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReconciliationFileParamsWithHTTPClient(client *http.Client) *GetReconciliationFileParams {
	var ()
	return &GetReconciliationFileParams{
		HTTPClient: client,
	}
}

/*GetReconciliationFileParams contains all the parameters to send to the API endpoint
for the get reconciliation file operation typically these are written to a http.Request
*/
type GetReconciliationFileParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get reconciliation file params
func (o *GetReconciliationFileParams) WithTimeout(timeout time.Duration) *GetReconciliationFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get reconciliation file params
func (o *GetReconciliationFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get reconciliation file params
func (o *GetReconciliationFileParams) WithContext(ctx context.Context) *GetReconciliationFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get reconciliation file params
func (o *GetReconciliationFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get reconciliation file params
func (o *GetReconciliationFileParams) WithHTTPClient(client *http.Client) *GetReconciliationFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get reconciliation file params
func (o *GetReconciliationFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get reconciliation file params
func (o *GetReconciliationFileParams) WithID(id int32) *GetReconciliationFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get reconciliation file params
func (o *GetReconciliationFileParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetReconciliationFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
