// Code generated by go-swagger; DO NOT EDIT.

package billing_statements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBillingRecordsFileParams creates a new GetBillingRecordsFileParams object
// with the default values initialized.
func NewGetBillingRecordsFileParams() *GetBillingRecordsFileParams {
	var ()
	return &GetBillingRecordsFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBillingRecordsFileParamsWithTimeout creates a new GetBillingRecordsFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBillingRecordsFileParamsWithTimeout(timeout time.Duration) *GetBillingRecordsFileParams {
	var ()
	return &GetBillingRecordsFileParams{

		timeout: timeout,
	}
}

// NewGetBillingRecordsFileParamsWithContext creates a new GetBillingRecordsFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBillingRecordsFileParamsWithContext(ctx context.Context) *GetBillingRecordsFileParams {
	var ()
	return &GetBillingRecordsFileParams{

		Context: ctx,
	}
}

// NewGetBillingRecordsFileParamsWithHTTPClient creates a new GetBillingRecordsFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBillingRecordsFileParamsWithHTTPClient(client *http.Client) *GetBillingRecordsFileParams {
	var ()
	return &GetBillingRecordsFileParams{
		HTTPClient: client,
	}
}

/*GetBillingRecordsFileParams contains all the parameters to send to the API endpoint
for the get billing records file operation typically these are written to a http.Request
*/
type GetBillingRecordsFileParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get billing records file params
func (o *GetBillingRecordsFileParams) WithTimeout(timeout time.Duration) *GetBillingRecordsFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get billing records file params
func (o *GetBillingRecordsFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get billing records file params
func (o *GetBillingRecordsFileParams) WithContext(ctx context.Context) *GetBillingRecordsFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get billing records file params
func (o *GetBillingRecordsFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get billing records file params
func (o *GetBillingRecordsFileParams) WithHTTPClient(client *http.Client) *GetBillingRecordsFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get billing records file params
func (o *GetBillingRecordsFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get billing records file params
func (o *GetBillingRecordsFileParams) WithID(id int32) *GetBillingRecordsFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get billing records file params
func (o *GetBillingRecordsFileParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBillingRecordsFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
