// Code generated by go-swagger; DO NOT EDIT.

package billing_statements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// GetBillingStatementsReader is a Reader for the GetBillingStatements structure.
type GetBillingStatementsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBillingStatementsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBillingStatementsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBillingStatementsOK creates a GetBillingStatementsOK with default headers values
func NewGetBillingStatementsOK() *GetBillingStatementsOK {
	return &GetBillingStatementsOK{}
}

/*GetBillingStatementsOK handles this case with default header values.

Success
*/
type GetBillingStatementsOK struct {
	Payload *models.APICollectionOfBillingStatement
}

func (o *GetBillingStatementsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/BillingStatements][%d] getBillingStatementsOK  %+v", 200, o.Payload)
}

func (o *GetBillingStatementsOK) GetPayload() *models.APICollectionOfBillingStatement {
	return o.Payload
}

func (o *GetBillingStatementsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICollectionOfBillingStatement)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
