// Code generated by go-swagger; DO NOT EDIT.

package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAddressesParams creates a new GetAddressesParams object
// with the default values initialized.
func NewGetAddressesParams() *GetAddressesParams {
	var ()
	return &GetAddressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAddressesParamsWithTimeout creates a new GetAddressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAddressesParamsWithTimeout(timeout time.Duration) *GetAddressesParams {
	var ()
	return &GetAddressesParams{

		timeout: timeout,
	}
}

// NewGetAddressesParamsWithContext creates a new GetAddressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAddressesParamsWithContext(ctx context.Context) *GetAddressesParams {
	var ()
	return &GetAddressesParams{

		Context: ctx,
	}
}

// NewGetAddressesParamsWithHTTPClient creates a new GetAddressesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAddressesParamsWithHTTPClient(client *http.Client) *GetAddressesParams {
	var ()
	return &GetAddressesParams{
		HTTPClient: client,
	}
}

/*GetAddressesParams contains all the parameters to send to the API endpoint
for the get addresses operation typically these are written to a http.Request
*/
type GetAddressesParams struct {

	/*OrganizationID*/
	OrganizationID int32
	/*Type*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get addresses params
func (o *GetAddressesParams) WithTimeout(timeout time.Duration) *GetAddressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get addresses params
func (o *GetAddressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get addresses params
func (o *GetAddressesParams) WithContext(ctx context.Context) *GetAddressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get addresses params
func (o *GetAddressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get addresses params
func (o *GetAddressesParams) WithHTTPClient(client *http.Client) *GetAddressesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get addresses params
func (o *GetAddressesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the get addresses params
func (o *GetAddressesParams) WithOrganizationID(organizationID int32) *GetAddressesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get addresses params
func (o *GetAddressesParams) SetOrganizationID(organizationID int32) {
	o.OrganizationID = organizationID
}

// WithType adds the typeVar to the get addresses params
func (o *GetAddressesParams) WithType(typeVar *string) *GetAddressesParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get addresses params
func (o *GetAddressesParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetAddressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", swag.FormatInt32(o.OrganizationID)); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
