// Code generated by go-swagger; DO NOT EDIT.

package reseller_sales_prices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// GetCurrentAsyncReader is a Reader for the GetCurrentAsync structure.
type GetCurrentAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCurrentAsyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCurrentAsyncOK creates a GetCurrentAsyncOK with default headers values
func NewGetCurrentAsyncOK() *GetCurrentAsyncOK {
	return &GetCurrentAsyncOK{}
}

/*GetCurrentAsyncOK handles this case with default header values.

Success
*/
type GetCurrentAsyncOK struct {
	Payload *models.ResellerSalesPrice
}

func (o *GetCurrentAsyncOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/ResellerSalesPrices/current][%d] getCurrentAsyncOK  %+v", 200, o.Payload)
}

func (o *GetCurrentAsyncOK) GetPayload() *models.ResellerSalesPrice {
	return o.Payload
}

func (o *GetCurrentAsyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResellerSalesPrice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
