// Code generated by go-swagger; DO NOT EDIT.

package reseller_sales_prices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// PostAsyncReader is a Reader for the PostAsync structure.
type PostAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAsyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAsyncOK creates a PostAsyncOK with default headers values
func NewPostAsyncOK() *PostAsyncOK {
	return &PostAsyncOK{}
}

/*PostAsyncOK handles this case with default header values.

Success
*/
type PostAsyncOK struct {
	Payload *models.ResellerSalesPrice
}

func (o *PostAsyncOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/ResellerSalesPrices][%d] postAsyncOK  %+v", 200, o.Payload)
}

func (o *PostAsyncOK) GetPayload() *models.ResellerSalesPrice {
	return o.Payload
}

func (o *PostAsyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResellerSalesPrice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
