// Code generated by go-swagger; DO NOT EDIT.

package reseller_sales_prices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewPutAsyncParams creates a new PutAsyncParams object
// with the default values initialized.
func NewPutAsyncParams() *PutAsyncParams {
	var ()
	return &PutAsyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAsyncParamsWithTimeout creates a new PutAsyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAsyncParamsWithTimeout(timeout time.Duration) *PutAsyncParams {
	var ()
	return &PutAsyncParams{

		timeout: timeout,
	}
}

// NewPutAsyncParamsWithContext creates a new PutAsyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAsyncParamsWithContext(ctx context.Context) *PutAsyncParams {
	var ()
	return &PutAsyncParams{

		Context: ctx,
	}
}

// NewPutAsyncParamsWithHTTPClient creates a new PutAsyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAsyncParamsWithHTTPClient(client *http.Client) *PutAsyncParams {
	var ()
	return &PutAsyncParams{
		HTTPClient: client,
	}
}

/*PutAsyncParams contains all the parameters to send to the API endpoint
for the put async operation typically these are written to a http.Request
*/
type PutAsyncParams struct {

	/*OldFromDate*/
	OldFromDate strfmt.DateTime
	/*ResellerSalesPrice*/
	ResellerSalesPrice *models.ResellerSalesPrice

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put async params
func (o *PutAsyncParams) WithTimeout(timeout time.Duration) *PutAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put async params
func (o *PutAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put async params
func (o *PutAsyncParams) WithContext(ctx context.Context) *PutAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put async params
func (o *PutAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put async params
func (o *PutAsyncParams) WithHTTPClient(client *http.Client) *PutAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put async params
func (o *PutAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOldFromDate adds the oldFromDate to the put async params
func (o *PutAsyncParams) WithOldFromDate(oldFromDate strfmt.DateTime) *PutAsyncParams {
	o.SetOldFromDate(oldFromDate)
	return o
}

// SetOldFromDate adds the oldFromDate to the put async params
func (o *PutAsyncParams) SetOldFromDate(oldFromDate strfmt.DateTime) {
	o.OldFromDate = oldFromDate
}

// WithResellerSalesPrice adds the resellerSalesPrice to the put async params
func (o *PutAsyncParams) WithResellerSalesPrice(resellerSalesPrice *models.ResellerSalesPrice) *PutAsyncParams {
	o.SetResellerSalesPrice(resellerSalesPrice)
	return o
}

// SetResellerSalesPrice adds the resellerSalesPrice to the put async params
func (o *PutAsyncParams) SetResellerSalesPrice(resellerSalesPrice *models.ResellerSalesPrice) {
	o.ResellerSalesPrice = resellerSalesPrice
}

// WriteToRequest writes these params to a swagger request
func (o *PutAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param oldFromDate
	if err := r.SetPathParam("oldFromDate", o.OldFromDate.String()); err != nil {
		return err
	}

	if o.ResellerSalesPrice != nil {
		if err := r.SetBodyParam(o.ResellerSalesPrice); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
