// Code generated by go-swagger; DO NOT EDIT.

package customer_tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewCreateCustomerTenantsParams creates a new CreateCustomerTenantsParams object
// with the default values initialized.
func NewCreateCustomerTenantsParams() *CreateCustomerTenantsParams {
	var ()
	return &CreateCustomerTenantsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCustomerTenantsParamsWithTimeout creates a new CreateCustomerTenantsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCustomerTenantsParamsWithTimeout(timeout time.Duration) *CreateCustomerTenantsParams {
	var ()
	return &CreateCustomerTenantsParams{

		timeout: timeout,
	}
}

// NewCreateCustomerTenantsParamsWithContext creates a new CreateCustomerTenantsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCustomerTenantsParamsWithContext(ctx context.Context) *CreateCustomerTenantsParams {
	var ()
	return &CreateCustomerTenantsParams{

		Context: ctx,
	}
}

// NewCreateCustomerTenantsParamsWithHTTPClient creates a new CreateCustomerTenantsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCustomerTenantsParamsWithHTTPClient(client *http.Client) *CreateCustomerTenantsParams {
	var ()
	return &CreateCustomerTenantsParams{
		HTTPClient: client,
	}
}

/*CreateCustomerTenantsParams contains all the parameters to send to the API endpoint
for the create customer tenants operation typically these are written to a http.Request
*/
type CreateCustomerTenantsParams struct {

	/*CustomerTenant*/
	CustomerTenant *models.CustomerTenantDetailed

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create customer tenants params
func (o *CreateCustomerTenantsParams) WithTimeout(timeout time.Duration) *CreateCustomerTenantsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create customer tenants params
func (o *CreateCustomerTenantsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create customer tenants params
func (o *CreateCustomerTenantsParams) WithContext(ctx context.Context) *CreateCustomerTenantsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create customer tenants params
func (o *CreateCustomerTenantsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create customer tenants params
func (o *CreateCustomerTenantsParams) WithHTTPClient(client *http.Client) *CreateCustomerTenantsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create customer tenants params
func (o *CreateCustomerTenantsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerTenant adds the customerTenant to the create customer tenants params
func (o *CreateCustomerTenantsParams) WithCustomerTenant(customerTenant *models.CustomerTenantDetailed) *CreateCustomerTenantsParams {
	o.SetCustomerTenant(customerTenant)
	return o
}

// SetCustomerTenant adds the customerTenant to the create customer tenants params
func (o *CreateCustomerTenantsParams) SetCustomerTenant(customerTenant *models.CustomerTenantDetailed) {
	o.CustomerTenant = customerTenant
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCustomerTenantsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CustomerTenant != nil {
		if err := r.SetBodyParam(o.CustomerTenant); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
