// Code generated by go-swagger; DO NOT EDIT.

package customer_tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// GetCustomerTenantByIDReader is a Reader for the GetCustomerTenantByID structure.
type GetCustomerTenantByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomerTenantByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomerTenantByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCustomerTenantByIDOK creates a GetCustomerTenantByIDOK with default headers values
func NewGetCustomerTenantByIDOK() *GetCustomerTenantByIDOK {
	return &GetCustomerTenantByIDOK{}
}

/*GetCustomerTenantByIDOK handles this case with default header values.

Success
*/
type GetCustomerTenantByIDOK struct {
	Payload *models.CustomerTenant
}

func (o *GetCustomerTenantByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/CustomerTenants/{id}][%d] getCustomerTenantByIdOK  %+v", 200, o.Payload)
}

func (o *GetCustomerTenantByIDOK) GetPayload() *models.CustomerTenant {
	return o.Payload
}

func (o *GetCustomerTenantByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerTenant)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
