// Code generated by go-swagger; DO NOT EDIT.

package customer_tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCustomerTenantDetailedByIDParams creates a new GetCustomerTenantDetailedByIDParams object
// with the default values initialized.
func NewGetCustomerTenantDetailedByIDParams() *GetCustomerTenantDetailedByIDParams {
	var ()
	return &GetCustomerTenantDetailedByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomerTenantDetailedByIDParamsWithTimeout creates a new GetCustomerTenantDetailedByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomerTenantDetailedByIDParamsWithTimeout(timeout time.Duration) *GetCustomerTenantDetailedByIDParams {
	var ()
	return &GetCustomerTenantDetailedByIDParams{

		timeout: timeout,
	}
}

// NewGetCustomerTenantDetailedByIDParamsWithContext creates a new GetCustomerTenantDetailedByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomerTenantDetailedByIDParamsWithContext(ctx context.Context) *GetCustomerTenantDetailedByIDParams {
	var ()
	return &GetCustomerTenantDetailedByIDParams{

		Context: ctx,
	}
}

// NewGetCustomerTenantDetailedByIDParamsWithHTTPClient creates a new GetCustomerTenantDetailedByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomerTenantDetailedByIDParamsWithHTTPClient(client *http.Client) *GetCustomerTenantDetailedByIDParams {
	var ()
	return &GetCustomerTenantDetailedByIDParams{
		HTTPClient: client,
	}
}

/*GetCustomerTenantDetailedByIDParams contains all the parameters to send to the API endpoint
for the get customer tenant detailed by Id operation typically these are written to a http.Request
*/
type GetCustomerTenantDetailedByIDParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) WithTimeout(timeout time.Duration) *GetCustomerTenantDetailedByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) WithContext(ctx context.Context) *GetCustomerTenantDetailedByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) WithHTTPClient(client *http.Client) *GetCustomerTenantDetailedByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) WithID(id int32) *GetCustomerTenantDetailedByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get customer tenant detailed by Id params
func (o *GetCustomerTenantDetailedByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomerTenantDetailedByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
