// Code generated by go-swagger; DO NOT EDIT.

package consumers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewAddConsumerParams creates a new AddConsumerParams object
// with the default values initialized.
func NewAddConsumerParams() *AddConsumerParams {
	var ()
	return &AddConsumerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddConsumerParamsWithTimeout creates a new AddConsumerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddConsumerParamsWithTimeout(timeout time.Duration) *AddConsumerParams {
	var ()
	return &AddConsumerParams{

		timeout: timeout,
	}
}

// NewAddConsumerParamsWithContext creates a new AddConsumerParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddConsumerParamsWithContext(ctx context.Context) *AddConsumerParams {
	var ()
	return &AddConsumerParams{

		Context: ctx,
	}
}

// NewAddConsumerParamsWithHTTPClient creates a new AddConsumerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddConsumerParamsWithHTTPClient(client *http.Client) *AddConsumerParams {
	var ()
	return &AddConsumerParams{
		HTTPClient: client,
	}
}

/*AddConsumerParams contains all the parameters to send to the API endpoint
for the add consumer operation typically these are written to a http.Request
*/
type AddConsumerParams struct {

	/*Consumer*/
	Consumer *models.Consumer

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add consumer params
func (o *AddConsumerParams) WithTimeout(timeout time.Duration) *AddConsumerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add consumer params
func (o *AddConsumerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add consumer params
func (o *AddConsumerParams) WithContext(ctx context.Context) *AddConsumerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add consumer params
func (o *AddConsumerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add consumer params
func (o *AddConsumerParams) WithHTTPClient(client *http.Client) *AddConsumerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add consumer params
func (o *AddConsumerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConsumer adds the consumer to the add consumer params
func (o *AddConsumerParams) WithConsumer(consumer *models.Consumer) *AddConsumerParams {
	o.SetConsumer(consumer)
	return o
}

// SetConsumer adds the consumer to the add consumer params
func (o *AddConsumerParams) SetConsumer(consumer *models.Consumer) {
	o.Consumer = consumer
}

// WriteToRequest writes these params to a swagger request
func (o *AddConsumerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Consumer != nil {
		if err := r.SetBodyParam(o.Consumer); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
