// Code generated by go-swagger; DO NOT EDIT.

package google_orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CheckoutAsyncReader is a Reader for the CheckoutAsync structure.
type CheckoutAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckoutAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckoutAsyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCheckoutAsyncOK creates a CheckoutAsyncOK with default headers values
func NewCheckoutAsyncOK() *CheckoutAsyncOK {
	return &CheckoutAsyncOK{}
}

/*CheckoutAsyncOK handles this case with default header values.

Success
*/
type CheckoutAsyncOK struct {
}

func (o *CheckoutAsyncOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/GoogleOrders/checkout][%d] checkoutAsyncOK ", 200)
}

func (o *CheckoutAsyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
