// Code generated by go-swagger; DO NOT EDIT.

package clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// CreateClientsReader is a Reader for the CreateClients structure.
type CreateClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateClientsOK creates a CreateClientsOK with default headers values
func NewCreateClientsOK() *CreateClientsOK {
	return &CreateClientsOK{}
}

/*CreateClientsOK handles this case with default header values.

Success
*/
type CreateClientsOK struct {
	Payload *models.Client
}

func (o *CreateClientsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/Clients][%d] createClientsOK  %+v", 200, o.Payload)
}

func (o *CreateClientsOK) GetPayload() *models.Client {
	return o.Payload
}

func (o *CreateClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Client)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
