// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddTagsAsyncReader is a Reader for the AddTagsAsync structure.
type AddTagsAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddTagsAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddTagsAsyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddTagsAsyncOK creates a AddTagsAsyncOK with default headers values
func NewAddTagsAsyncOK() *AddTagsAsyncOK {
	return &AddTagsAsyncOK{}
}

/*AddTagsAsyncOK handles this case with default header values.

Success
*/
type AddTagsAsyncOK struct {
}

func (o *AddTagsAsyncOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/Assets/{assetId}/tags][%d] addTagsAsyncOK ", 200)
}

func (o *AddTagsAsyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
