// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewVerifyAsyncParams creates a new VerifyAsyncParams object
// with the default values initialized.
func NewVerifyAsyncParams() *VerifyAsyncParams {
	var ()
	return &VerifyAsyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyAsyncParamsWithTimeout creates a new VerifyAsyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVerifyAsyncParamsWithTimeout(timeout time.Duration) *VerifyAsyncParams {
	var ()
	return &VerifyAsyncParams{

		timeout: timeout,
	}
}

// NewVerifyAsyncParamsWithContext creates a new VerifyAsyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewVerifyAsyncParamsWithContext(ctx context.Context) *VerifyAsyncParams {
	var ()
	return &VerifyAsyncParams{

		Context: ctx,
	}
}

// NewVerifyAsyncParamsWithHTTPClient creates a new VerifyAsyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVerifyAsyncParamsWithHTTPClient(client *http.Client) *VerifyAsyncParams {
	var ()
	return &VerifyAsyncParams{
		HTTPClient: client,
	}
}

/*VerifyAsyncParams contains all the parameters to send to the API endpoint
for the verify async operation typically these are written to a http.Request
*/
type VerifyAsyncParams struct {

	/*Order*/
	Order *models.AssetOrder

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the verify async params
func (o *VerifyAsyncParams) WithTimeout(timeout time.Duration) *VerifyAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify async params
func (o *VerifyAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify async params
func (o *VerifyAsyncParams) WithContext(ctx context.Context) *VerifyAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify async params
func (o *VerifyAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify async params
func (o *VerifyAsyncParams) WithHTTPClient(client *http.Client) *VerifyAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify async params
func (o *VerifyAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the verify async params
func (o *VerifyAsyncParams) WithOrder(order *models.AssetOrder) *VerifyAsyncParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the verify async params
func (o *VerifyAsyncParams) SetOrder(order *models.AssetOrder) {
	o.Order = order
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Order != nil {
		if err := r.SetBodyParam(o.Order); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
