// Code generated by go-swagger; DO NOT EDIT.

package product_containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bjerkio/crayon-api-go/models"
)

// NewUpdateProductContainersParams creates a new UpdateProductContainersParams object
// with the default values initialized.
func NewUpdateProductContainersParams() *UpdateProductContainersParams {
	var (
		requireEulaAnalysisDefault = bool(false)
	)
	return &UpdateProductContainersParams{
		RequireEulaAnalysis: &requireEulaAnalysisDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProductContainersParamsWithTimeout creates a new UpdateProductContainersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateProductContainersParamsWithTimeout(timeout time.Duration) *UpdateProductContainersParams {
	var (
		requireEulaAnalysisDefault = bool(false)
	)
	return &UpdateProductContainersParams{
		RequireEulaAnalysis: &requireEulaAnalysisDefault,

		timeout: timeout,
	}
}

// NewUpdateProductContainersParamsWithContext creates a new UpdateProductContainersParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateProductContainersParamsWithContext(ctx context.Context) *UpdateProductContainersParams {
	var (
		requireEulaAnalysisDefault = bool(false)
	)
	return &UpdateProductContainersParams{
		RequireEulaAnalysis: &requireEulaAnalysisDefault,

		Context: ctx,
	}
}

// NewUpdateProductContainersParamsWithHTTPClient creates a new UpdateProductContainersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateProductContainersParamsWithHTTPClient(client *http.Client) *UpdateProductContainersParams {
	var (
		requireEulaAnalysisDefault = bool(false)
	)
	return &UpdateProductContainersParams{
		RequireEulaAnalysis: &requireEulaAnalysisDefault,
		HTTPClient:          client,
	}
}

/*UpdateProductContainersParams contains all the parameters to send to the API endpoint
for the update product containers operation typically these are written to a http.Request
*/
type UpdateProductContainersParams struct {

	/*ID*/
	ID int32
	/*ProductContainer*/
	ProductContainer *models.ProductContainer
	/*RequireEulaAnalysis*/
	RequireEulaAnalysis *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update product containers params
func (o *UpdateProductContainersParams) WithTimeout(timeout time.Duration) *UpdateProductContainersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update product containers params
func (o *UpdateProductContainersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update product containers params
func (o *UpdateProductContainersParams) WithContext(ctx context.Context) *UpdateProductContainersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update product containers params
func (o *UpdateProductContainersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update product containers params
func (o *UpdateProductContainersParams) WithHTTPClient(client *http.Client) *UpdateProductContainersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update product containers params
func (o *UpdateProductContainersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update product containers params
func (o *UpdateProductContainersParams) WithID(id int32) *UpdateProductContainersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update product containers params
func (o *UpdateProductContainersParams) SetID(id int32) {
	o.ID = id
}

// WithProductContainer adds the productContainer to the update product containers params
func (o *UpdateProductContainersParams) WithProductContainer(productContainer *models.ProductContainer) *UpdateProductContainersParams {
	o.SetProductContainer(productContainer)
	return o
}

// SetProductContainer adds the productContainer to the update product containers params
func (o *UpdateProductContainersParams) SetProductContainer(productContainer *models.ProductContainer) {
	o.ProductContainer = productContainer
}

// WithRequireEulaAnalysis adds the requireEulaAnalysis to the update product containers params
func (o *UpdateProductContainersParams) WithRequireEulaAnalysis(requireEulaAnalysis *bool) *UpdateProductContainersParams {
	o.SetRequireEulaAnalysis(requireEulaAnalysis)
	return o
}

// SetRequireEulaAnalysis adds the requireEulaAnalysis to the update product containers params
func (o *UpdateProductContainersParams) SetRequireEulaAnalysis(requireEulaAnalysis *bool) {
	o.RequireEulaAnalysis = requireEulaAnalysis
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProductContainersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.ProductContainer != nil {
		if err := r.SetBodyParam(o.ProductContainer); err != nil {
			return err
		}
	}

	if o.RequireEulaAnalysis != nil {

		// query param requireEulaAnalysis
		var qrRequireEulaAnalysis bool
		if o.RequireEulaAnalysis != nil {
			qrRequireEulaAnalysis = *o.RequireEulaAnalysis
		}
		qRequireEulaAnalysis := swag.FormatBool(qrRequireEulaAnalysis)
		if qRequireEulaAnalysis != "" {
			if err := r.SetQueryParam("requireEulaAnalysis", qRequireEulaAnalysis); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
