// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActivationLink activation link
//
// swagger:model ActivationLink
type ActivationLink struct {

	// subscription Id
	SubscriptionID string `json:"SubscriptionId,omitempty"`

	// Uri
	URI string `json:"Uri,omitempty"`
}

// Validate validates this activation link
func (m *ActivationLink) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActivationLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivationLink) UnmarshalBinary(b []byte) error {
	var res ActivationLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
