// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgreementIdentityReference agreement identity reference
//
// swagger:model AgreementIdentityReference
type AgreementIdentityReference struct {

	// agreement number
	AgreementNumber string `json:"AgreementNumber,omitempty"`

	// commitment level
	CommitmentLevel float64 `json:"CommitmentLevel,omitempty"`

	// Id
	ID int32 `json:"Id,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this agreement identity reference
func (m *AgreementIdentityReference) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgreementIdentityReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgreementIdentityReference) UnmarshalBinary(b []byte) error {
	var res AgreementIdentityReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
