// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgreementIdentityReferenceDto agreement identity reference dto
//
// swagger:model AgreementIdentityReferenceDto
type AgreementIdentityReferenceDto struct {

	// agreement number
	AgreementNumber string `json:"AgreementNumber,omitempty"`

	// commitment level
	CommitmentLevel float64 `json:"CommitmentLevel,omitempty"`

	// Id
	ID int32 `json:"Id,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this agreement identity reference dto
func (m *AgreementIdentityReferenceDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgreementIdentityReferenceDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgreementIdentityReferenceDto) UnmarshalBinary(b []byte) error {
	var res AgreementIdentityReferenceDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
