// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssetOrderLineError asset order line error
//
// swagger:model AssetOrderLineError
type AssetOrderLineError struct {

	// description
	Description string `json:"Description,omitempty"`

	// properties
	Properties map[string]string `json:"Properties,omitempty"`

	// reason code
	ReasonCode string `json:"ReasonCode,omitempty"`
}

// Validate validates this asset order line error
func (m *AssetOrderLineError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssetOrderLineError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetOrderLineError) UnmarshalBinary(b []byte) error {
	var res AssetOrderLineError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
