// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustomerTenantAddress customer tenant address
//
// swagger:model CustomerTenantAddress
type CustomerTenantAddress struct {

	// address line1
	AddressLine1 string `json:"AddressLine1,omitempty"`

	// address line2
	AddressLine2 string `json:"AddressLine2,omitempty"`

	// address line3
	AddressLine3 string `json:"AddressLine3,omitempty"`

	// city
	City string `json:"City,omitempty"`

	// country code
	CountryCode string `json:"CountryCode,omitempty"`

	// country name
	CountryName string `json:"CountryName,omitempty"`

	// first name
	FirstName string `json:"FirstName,omitempty"`

	// last name
	LastName string `json:"LastName,omitempty"`

	// postal code
	PostalCode string `json:"PostalCode,omitempty"`

	// region
	Region string `json:"Region,omitempty"`
}

// Validate validates this customer tenant address
func (m *CustomerTenantAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomerTenantAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomerTenantAddress) UnmarshalBinary(b []byte) error {
	var res CustomerTenantAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
