// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomerTenant customer tenant
//
// swagger:model CustomerTenant
type CustomerTenant struct {

	// consumer
	Consumer *ObjectReference `json:"Consumer,omitempty"`

	// customer tenant type
	// Enum: [None T1 T2]
	CustomerTenantType string `json:"CustomerTenantType,omitempty"`

	// default subscription price type
	// Enum: [PurchasePrice ListPrice FixedPrice]
	DefaultSubscriptionPriceType string `json:"DefaultSubscriptionPriceType,omitempty"`

	// domain
	Domain string `json:"Domain,omitempty"`

	// domain prefix
	DomainPrefix string `json:"DomainPrefix,omitempty"`

	// entity status
	// Enum: [None Removed]
	EntityStatus string `json:"EntityStatus,omitempty"`

	// external publisher customer Id
	ExternalPublisherCustomerID string `json:"ExternalPublisherCustomerId,omitempty"`

	// Id
	ID int32 `json:"Id,omitempty"`

	// invoice profile
	InvoiceProfile *ObjectReference `json:"InvoiceProfile,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// organization
	Organization *Organization `json:"Organization,omitempty"`

	// program
	Program *ObjectReference `json:"Program,omitempty"`

	// publisher
	Publisher *ObjectReference `json:"Publisher,omitempty"`

	// publisher customer Id
	PublisherCustomerID string `json:"PublisherCustomerId,omitempty"`

	// reference
	Reference string `json:"Reference,omitempty"`

	// reseller markup
	ResellerMarkup float64 `json:"ResellerMarkup,omitempty"`

	// agreement
	Agreement *CustomerTenantAgreement `json:"agreement,omitempty"`
}

// Validate validates this customer tenant
func (m *CustomerTenant) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsumer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomerTenantType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultSubscriptionPriceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntityStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInvoiceProfile(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganization(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProgram(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublisher(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAgreement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustomerTenant) validateConsumer(formats strfmt.Registry) error {

	if swag.IsZero(m.Consumer) { // not required
		return nil
	}

	if m.Consumer != nil {
		if err := m.Consumer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Consumer")
			}
			return err
		}
	}

	return nil
}

var customerTenantTypeCustomerTenantTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["None","T1","T2"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customerTenantTypeCustomerTenantTypePropEnum = append(customerTenantTypeCustomerTenantTypePropEnum, v)
	}
}

const (

	// CustomerTenantCustomerTenantTypeNone captures enum value "None"
	CustomerTenantCustomerTenantTypeNone string = "None"

	// CustomerTenantCustomerTenantTypeT1 captures enum value "T1"
	CustomerTenantCustomerTenantTypeT1 string = "T1"

	// CustomerTenantCustomerTenantTypeT2 captures enum value "T2"
	CustomerTenantCustomerTenantTypeT2 string = "T2"
)

// prop value enum
func (m *CustomerTenant) validateCustomerTenantTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customerTenantTypeCustomerTenantTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomerTenant) validateCustomerTenantType(formats strfmt.Registry) error {

	if swag.IsZero(m.CustomerTenantType) { // not required
		return nil
	}

	// value enum
	if err := m.validateCustomerTenantTypeEnum("CustomerTenantType", "body", m.CustomerTenantType); err != nil {
		return err
	}

	return nil
}

var customerTenantTypeDefaultSubscriptionPriceTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PurchasePrice","ListPrice","FixedPrice"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customerTenantTypeDefaultSubscriptionPriceTypePropEnum = append(customerTenantTypeDefaultSubscriptionPriceTypePropEnum, v)
	}
}

const (

	// CustomerTenantDefaultSubscriptionPriceTypePurchasePrice captures enum value "PurchasePrice"
	CustomerTenantDefaultSubscriptionPriceTypePurchasePrice string = "PurchasePrice"

	// CustomerTenantDefaultSubscriptionPriceTypeListPrice captures enum value "ListPrice"
	CustomerTenantDefaultSubscriptionPriceTypeListPrice string = "ListPrice"

	// CustomerTenantDefaultSubscriptionPriceTypeFixedPrice captures enum value "FixedPrice"
	CustomerTenantDefaultSubscriptionPriceTypeFixedPrice string = "FixedPrice"
)

// prop value enum
func (m *CustomerTenant) validateDefaultSubscriptionPriceTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customerTenantTypeDefaultSubscriptionPriceTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomerTenant) validateDefaultSubscriptionPriceType(formats strfmt.Registry) error {

	if swag.IsZero(m.DefaultSubscriptionPriceType) { // not required
		return nil
	}

	// value enum
	if err := m.validateDefaultSubscriptionPriceTypeEnum("DefaultSubscriptionPriceType", "body", m.DefaultSubscriptionPriceType); err != nil {
		return err
	}

	return nil
}

var customerTenantTypeEntityStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["None","Removed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customerTenantTypeEntityStatusPropEnum = append(customerTenantTypeEntityStatusPropEnum, v)
	}
}

const (

	// CustomerTenantEntityStatusNone captures enum value "None"
	CustomerTenantEntityStatusNone string = "None"

	// CustomerTenantEntityStatusRemoved captures enum value "Removed"
	CustomerTenantEntityStatusRemoved string = "Removed"
)

// prop value enum
func (m *CustomerTenant) validateEntityStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customerTenantTypeEntityStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomerTenant) validateEntityStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.EntityStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateEntityStatusEnum("EntityStatus", "body", m.EntityStatus); err != nil {
		return err
	}

	return nil
}

func (m *CustomerTenant) validateInvoiceProfile(formats strfmt.Registry) error {

	if swag.IsZero(m.InvoiceProfile) { // not required
		return nil
	}

	if m.InvoiceProfile != nil {
		if err := m.InvoiceProfile.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("InvoiceProfile")
			}
			return err
		}
	}

	return nil
}

func (m *CustomerTenant) validateOrganization(formats strfmt.Registry) error {

	if swag.IsZero(m.Organization) { // not required
		return nil
	}

	if m.Organization != nil {
		if err := m.Organization.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Organization")
			}
			return err
		}
	}

	return nil
}

func (m *CustomerTenant) validateProgram(formats strfmt.Registry) error {

	if swag.IsZero(m.Program) { // not required
		return nil
	}

	if m.Program != nil {
		if err := m.Program.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Program")
			}
			return err
		}
	}

	return nil
}

func (m *CustomerTenant) validatePublisher(formats strfmt.Registry) error {

	if swag.IsZero(m.Publisher) { // not required
		return nil
	}

	if m.Publisher != nil {
		if err := m.Publisher.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Publisher")
			}
			return err
		}
	}

	return nil
}

func (m *CustomerTenant) validateAgreement(formats strfmt.Registry) error {

	if swag.IsZero(m.Agreement) { // not required
		return nil
	}

	if m.Agreement != nil {
		if err := m.Agreement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("agreement")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustomerTenant) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomerTenant) UnmarshalBinary(b []byte) error {
	var res CustomerTenant
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
