// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ManagementLinkGrouped management link grouped
//
// swagger:model ManagementLinkGrouped
type ManagementLinkGrouped struct {

	// link
	Link string `json:"Link,omitempty"`

	// reseller customer
	ResellerCustomer *ObjectReference `json:"ResellerCustomer,omitempty"`

	// text
	Text string `json:"Text,omitempty"`
}

// Validate validates this management link grouped
func (m *ManagementLinkGrouped) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResellerCustomer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManagementLinkGrouped) validateResellerCustomer(formats strfmt.Registry) error {

	if swag.IsZero(m.ResellerCustomer) { // not required
		return nil
	}

	if m.ResellerCustomer != nil {
		if err := m.ResellerCustomer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ResellerCustomer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ManagementLinkGrouped) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ManagementLinkGrouped) UnmarshalBinary(b []byte) error {
	var res ManagementLinkGrouped
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
