// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrganizationSalesContact organization sales contact
//
// swagger:model OrganizationSalesContact
type OrganizationSalesContact struct {

	// email
	Email string `json:"Email,omitempty"`

	// full name
	FullName string `json:"FullName,omitempty"`

	// phone
	Phone string `json:"Phone,omitempty"`
}

// Validate validates this organization sales contact
func (m *OrganizationSalesContact) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationSalesContact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationSalesContact) UnmarshalBinary(b []byte) error {
	var res OrganizationSalesContact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
