// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductInformation product information
//
// swagger:model ProductInformation
type ProductInformation struct {

	// culture code
	CultureCode string `json:"CultureCode,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// external product Id
	ExternalProductID int32 `json:"ExternalProductId,omitempty"`

	// learn more link
	LearnMoreLink string `json:"LearnMoreLink,omitempty"`
}

// Validate validates this product information
func (m *ProductInformation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductInformation) UnmarshalBinary(b []byte) error {
	var res ProductInformation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
